---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    - htop-osx
    - watch
    - rsync
    - git-flow
    - ansible
    - autoconf
    - bash-completion
    - boot2docker
    - docker
    - gettext
    - go
    - gpg
    - hub
    - iperf
    - libdvdcss
    - libevent
    - packer
    - python
    - sqlite
    - mcrypt
    - ssh-copy-id
    - ios-sim
    - readline
    - subversion
    - kdiff3
    - openssl
    - pv
    - wrk
    - brew-cask
    - mongodb

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - imageoptim
    - phpstorm
    - sequel-pro
    - java6
    - java7
    - java
    - adium
    - bettertouchtool
    - google-chrome
    - dropbox
    - fing
    - firefox
    - handbrake
    - karabiner
    - limechat
    - licecap
    - macvim
    - menumeters
    - nvalt
    - sequel-pro
    - skype
    - skitch
    - seil
    - sublime-text 
    - textmate
    - timemachineeditor
    - tower
    - transmit
    - vagrant
    - vagrant-manager
    - vlc
    - virtualbox