---
#If you can, change this...

mysql_root_password: "y0u$houldReallyChangeMe"

#at your discretion, but I find it works best here
website_path: "/var/sites"

#If you can edit, you should - but git has to have something
git_user_name: "{{ ansible_user_id }}"
git_user_email: "{{ ansible_user_id }}@slac.stanford.edu"

#Which SLAC Sites do you want locally?
#Repo is the github repository
#Site-name will be directory, url and db name
slac_sites:
  - repo: https://github.com/SLAC-OCIO/slac-www.git
    site_name: slac-www
  - repo: https://github.com/SLAC-OCIO/slac-features.git
    site_name: slac-features
  - repo: https://github.com/SLAC-OCIO/slac-gtw.git
    site_name: slac-gtw
    
#do not change after this line
drush_install_path: /usr/local/share/drush
drush_version: "master"
drush_keep_updated: no
drush_force_update: no
composer_path: /usr/local/bin/composer
composer_home_owner: root
composer_home_group: wheel
#do not change before this line