---

- hosts: 127.0.0.1
  connection: local
  
  tasks:
    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh

    - name: Improve ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config

    - name: Add to user to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^{{ansible_user_id}}', line: '{{ansible_user_id}} ALL=(ALL) NOPASSWD: ALL' }

    - name: Create user bin directory
      file:
        path: "~/bin"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "staff"
        mode: 0755

    - name: Copy vhost script
      copy: 
        src: "~/.slac-mac/virtualhost.sh" 
        dest: "~/bin/virtualhost.sh" 
        owner: "{{ ansible_user_id }}"
        group: "staff" 
        mode: 0655

    - name: copy vhost script conf
      copy: 
        src: "~/.slac-mac/virtualhost.sh.conf" 
        dest: "~/bin/virtualhost.sh.conf" 
        owner: "{{ ansible_user_id }}"
        group: "staff" 
        mode: 0655
  roles:
    - profile-all
    - profile-developer