---

- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh
        - /etc/apache2/virtualhosts
    
    - name: personal ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config
    
    - name: copy virtualhost files
      become: yes
      file:
        src: "files/{{item}}"
        path: "/etc/apache2/virtualhosts"
        owner: root
        group: wheel
        mode: 0655
      with_items:
        - slac_features.conf
        - slac_gtw.conf
        - slac_www.conf
    - git: repo=ssh://git@github.com/mylogin/hello.git 
        dest=/home/mylogin/hello
          
    - name: restart apache2
      service: apache2
      state: restart

    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^{{ansible_user_id}}', line: '{{ansible_user_id}} ALL=(ALL) NOPASSWD: ALL' }

    - name: create user bin
      file:
        path: "{{ ansible_user_id }}/bin"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0755

    - name: copy vhost script
      copy: 
        src: "~/.slac-mac/virtualhost.sh" 
        dest: "~/bin/virtualhost.sh" 
        owner: "{{ ansible_user_id }}"
        group: users 
        mode: 0655

    - name: copy vhost script conf
      copy: 
        src: "~/.slac-mac/virtualhost.sh.conf" 
        dest: "~/bin/virtualhost.sh.conf" 
        owner: "{{ ansible_user_id }}"
        group: users 
        mode: 0655
  roles:
    - profile-all
    - profile-developer

  vars:
    - computername: "{{ ansible_user_id }}"
    - git_user_name: "{{ ansible_user_id }}"
    - git_user_email: "{{ ansible_user_id }}@slac.stanford.edu"
    - mysql_root_password: "y0u$houldReallyChangeMe"
    - sublime_packages:
        - dest: "SideBarEnhancements"
          repo: "https://github.com/titoBouzout/SideBarEnhancements"
          version: "st3"
        - dest: "GitGutter"
          repo: "https://github.com/jisaacks/GitGutter.git"
          version: "master"
        - dest: "BracketHighlighter"
          repo: "https://github.com/facelessuser/BracketHighlighter.git"
          version: "master"
        - dest: "Base16"
          repo: "https://github.com/chriskempson/base16-textmate.git"
          version: "master"
        - dest: "Theme - Soda"
          repo: "https://github.com/buymeasoda/soda-theme.git"
          version: "master"
        - dest: "ApplySyntax"
          repo: "https://github.com/facelessuser/ApplySyntax.git"
          version: "master"
        - dest: "SublimeAllAutocomplete"
          repo: "https://github.com/alienhard/SublimeAllAutocomplete"
          version: "master"
        - dest: "Ansible"
          repo: "https://github.com/clifford-github/sublime-ansible.git"
          version: "master"
    
