---

- hosts: 127.0.0.1
  connection: local
  
  tasks:
    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh

    - name: Improve ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config

    - name: Add to user to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^{{ansible_user_id}}', line: '{{ansible_user_id}} ALL=(ALL) NOPASSWD: ALL' }

    - name: Create user bin directory
      file:
        path: "~/bin"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "staff"
        mode: 0755

  roles:
    - profile-all
    - profile-developer
  vars:
    username: "{{ ansible_user_id }}"
    computername: "{{ ansible_user_id }}"
    git_user_name: "{{ username }}"
    git_user_email: "{{ ansible_user_id }}@slac.stanford.edu"

    git_config:
          user:
            name:  "{{ ansible_user_id }}"
            email: "{{ ansible_user_id }}@slac.stanford.edu"
          color:
            branch: auto
            diff: auto
            interactive: auto
            status: auto
            ui: auto
          core:
            editor: vim
            excludesfile: "~/.gitexcludesfile"
          push:
            default: current
          alias:
            clo: clone
            co: checkout
            st: status
            pur: pull --rebase
            ci: commit
            rc: rebase --continue
            lg: log -M --decorate --graph --oneline
            br: branch
            sth: stash

          git_ignore:
          - "*.log"
          - ".vagrant"
          # OS generated files
          - ".DS_Store"
          - ".DS_Store?"
          - "._*"
          - ".Spotlight-V100"
          - ".Trashes"
          - "Icon?"
          - "ehthumbs.db"
          - "Thumbs.db"
          # ide
          - "~*"
          - ".idea/"