---

- hosts: 127.0.0.1
  connection: local
  
  tasks:
    - name: create ssh directory
      become: yes
      file:
        path: '{{item}}'
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh

    - name: Improve ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config

    - name: Add to user to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp='{{ item.regexp }}'
        line='{{ item.line }}'
        state=present
        create=true
      with_items:
        - { regexp: '^{{ansible_user_id}}', line: '{{ansible_user_id}} ALL=(ALL) NOPASSWD: ALL' }

  roles:
    - profile-all

  vars:
    
    username: '{{ ansible_user_id }}'
    computername: '{{ ansible_user_id }}'
    git_user_name: '{{ username }}'
    git_user_email: '{{ ansible_user_id }}@slac.stanford.edu'