---
- src: https://github.com/slac-ocio/ansible-role-homebrew.git
  name: slac.grail-homebrew

- src: https://github.com/slac-ocio/ansible-role-cli.git
  name: slac.grail-cli

- src: https://github.com/SLAC-OCIO/ansible-role-osx-defaults.git
  name: slac.grail-osx-defaults

- src: https://github.com/slac-ocio/ansible-role-computername.git
  name: slac.grail-computername

- src: https://github.com/slac-ocio/ansible-role-mysql.git
  name: slac.grail-mysql
  
- src: https://github.com/slac-ocio/ansible-role-php.git
  name: slac.grail-php

- src: https://github.com/slac-ocio/ansible-role-sublimetext.git
  name: slac.grail-sublimetext

- src: https://github.com/slac-ocio/ansible-role-node.git
  name: slac.grail-node

- src: https://github.com/slac-ocio/ansible-role-vim.git
  name: slac.grail-vim

- src: https://github.com/slac-ocio/ansible-role-drush.git
  name: slac.grail-drush

- src: https://github.com/slac-ocio/ansible-role-composer
  name: slac.grail-composer
  
- src: https://github.com/slac-ocio/ansible-slac-sites-build.git
  name: slac.grail-sites-build

- src: https://github.com/kosssi/ansible-role-gitconfig.git
  name: kossi.gitconfig
