---

- src: https://github.com/slac-ocio/ansible-role-homebrew.git
  name: slac.superlumic-homebrew

- src: https://github.com/slac-ocio/ansible-role-cli.git
  name: slac.superlumic-cli

- src: https://github.com/slac-ocio/ansible-role-osx-defaults.git
  name: slac.superlumic-osx-defaults

- src: https://github.com/slac-ocio/ansible-role-computername.git
  name: slac.superlumic-computername

- src: https://github.com/slac-ocio/ansible-role-mysql.git
  name: slac.superlumic-mysql

- src: https://github.com/slac-ocio/ansible-role-php.git
  name: slac.superlumic-php

- src: https://github.com/slac-ocio/ansible-role-sublimetext.git
  name: slac.superlumic-sublimetext

- src: https://github.com/slac-ocio/ansible-role-node.git
  name: slac.superlumic-node

- src: https://github.com/slac-ocio/ansible-role-postgresql.git
  name: slac.superlumic-postgresql

- src: https://github.com/slac-ocio/ansible-role-vim.git
  name: slac.superlumic-vim

- src: https://github.com/slac-ocio/ansible-role-modjk.git
  name: slac.superlumic-modjk

- src: https://github.com/slac-ocio/ansible-role-skylab.git
  name: slac.superlumic-skylab

- src: https://github.com/slac-ocio/ansible-role-drush.git
  name: slac.drush

- src: https://github.com/geerlingguy/ansible-role-composer
  name: slac.composer
