---
#TODO: Make a node/meteor profile
- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  ignore_errors: yes
  with_items:
    - slack
    - google-drive
    - vlc
    - amphetamine
    - google-chrome
    - firefox
    - iterm2
