---
galaxy_info:
  author: Vincent Flesouras
  description: Ansible profile role for all users
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - slac.grail-computername
  - slac.grail-cli
