---
galaxy_info:
  author: Vincent Flesouras
  description: Ansible profile role for Drupal developers
  license: MIT
  min_ansible_version: 1.3
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - slac.grail-computername
  - slac.grail-cli
  - slac.grail-homebrew
  - slac.grail-mysql
  - slac.grail-php
  - slac.grail-sublimetext
  - slac.grail-node
  - slac.grail-vim
  - slac.grail-composer
  - slac.grail-drush
  - slac.grail-sites-build
  - profile-all